package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestCheck(t *testing.T) {
	tests := []struct {
		input    int
		expected string
	}{
		{input: 1, expected: "1"},
		{input: 2, expected: "2"},
		{input: 3, expected: "Fizz"},
		{input: 4, expected: "4"},
		{input: 5, expected: "Buzz"},
		{input: 6, expected: "Fizz"},
		{input: 7, expected: "7"},
		{input: 8, expected: "8"},
		{input: 9, expected: "Fizz"},
		{input: 10, expected: "Buzz"},
		{input: 11, expected: "11"},
		{input: 12, expected: "Fizz"},
		{input: 13, expected: "13"},
		{input: 14, expected: "14"},
		{input: 15, expected: "Fizz Buzz"},
		{input: 16, expected: "16"},
		{input: 17, expected: "17"},
		{input: 18, expected: "Fizz"},
		{input: 19, expected: "19"},
		{input: 20, expected: "Buzz"},
		{input: 21, expected: "Fizz"},
		{input: 22, expected: "22"},
		{input: 23, expected: "23"},
		{input: 24, expected: "Fizz"},
		{input: 25, expected: "Buzz"},
		{input: 26, expected: "26"},
		{input: 27, expected: "Fizz"},
		{input: 28, expected: "28"},
		{input: 29, expected: "29"},
		{input: 30, expected: "Fizz Buzz"},
		{input: 31, expected: "31"},
		{input: 32, expected: "32"},
		{input: 33, expected: "Fizz"},
		{input: 34, expected: "34"},
		{input: 35, expected: "Buzz"},
		{input: 36, expected: "Fizz"},
		{input: 37, expected: "37"},
		{input: 38, expected: "38"},
		{input: 39, expected: "Fizz"},
		{input: 40, expected: "Buzz"},
		{input: 41, expected: "41"},
		{input: 42, expected: "Fizz"},
		{input: 43, expected: "43"},
		{input: 44, expected: "44"},
		{input: 45, expected: "Fizz Buzz"},
		{input: 46, expected: "46"},
		{input: 47, expected: "47"},
		{input: 48, expected: "Fizz"},
		{input: 49, expected: "49"},
		{input: 50, expected: "Buzz"},
		{input: 51, expected: "Fizz"},
		{input: 52, expected: "52"},
		{input: 53, expected: "53"},
		{input: 54, expected: "Fizz"},
		{input: 55, expected: "Buzz"},
		{input: 56, expected: "56"},
		{input: 57, expected: "Fizz"},
		{input: 58, expected: "58"},
		{input: 59, expected: "59"},
		{input: 60, expected: "Fizz Buzz"},
		{input: 61, expected: "61"},
		{input: 62, expected: "62"},
		{input: 63, expected: "Fizz"},
		{input: 64, expected: "64"},
		{input: 65, expected: "Buzz"},
		{input: 66, expected: "Fizz"},
		{input: 67, expected: "67"},
		{input: 68, expected: "68"},
		{input: 69, expected: "Fizz"},
		{input: 70, expected: "Buzz"},
		{input: 71, expected: "71"},
		{input: 72, expected: "Fizz"},
		{input: 73, expected: "73"},
		{input: 74, expected: "74"},
		{input: 75, expected: "Fizz Buzz"},
		{input: 76, expected: "76"},
		{input: 77, expected: "77"},
		{input: 78, expected: "Fizz"},
		{input: 79, expected: "79"},
		{input: 80, expected: "Buzz"},
		{input: 81, expected: "Fizz"},
		{input: 82, expected: "82"},
		{input: 83, expected: "83"},
		{input: 84, expected: "Fizz"},
		{input: 85, expected: "Buzz"},
		{input: 86, expected: "86"},
		{input: 87, expected: "Fizz"},
		{input: 88, expected: "88"},
		{input: 89, expected: "89"},
		{input: 90, expected: "Fizz Buzz"},
		{input: 91, expected: "91"},
		{input: 92, expected: "92"},
		{input: 93, expected: "Fizz"},
		{input: 94, expected: "94"},
		{input: 95, expected: "Buzz"},
		{input: 96, expected: "Fizz"},
		{input: 97, expected: "97"},
		{input: 98, expected: "98"},
		{input: 99, expected: "Fizz"},
		{input: 100, expected: "Buzz"},
	}

	for _, tc := range tests {
		assert.Equal(t, check(tc.input), tc.expected)
	}
}
